<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class YouTubeService
{
    protected $apiKey;
    protected $baseUrl = 'https://www.googleapis.com/youtube/v3';

    public function __construct()
    {
        $this->apiKey = config('services.youtube.api_key');
        
        if (!$this->apiKey) {
            throw new \Exception('YOUTUBE_API_KEY is not set in .env');
        }
    }

    /**
     * Search for videos on YouTube
     * 
     * @param string $query
     * @param int $maxResults
     * @return array
     */
    public function search(string $query, int $maxResults = 5)
    {
        try {
            $response = Http::get("{$this->baseUrl}/search", [
                'part' => 'snippet',
                'q' => $query,
                'type' => 'video',
                'maxResults' => $maxResults,
                'key' => $this->apiKey,
                'videoEmbeddable' => 'true', // Only get songs we can play
            ]);

            if ($response->failed()) {
                Log::error('YouTube API Search Error: ' . $response->body());
                return ['error' => 'YouTube API request failed', 'details' => $response->json()];
            }

            return $response->json();
        } catch (\Exception $e) {
            Log::error('YouTube Service Search Exception: ' . $e->getMessage());
            return ['error' => 'Internal Server Error', 'message' => $e->getMessage()];
        }
    }

    /**
     * Get details for specific video IDs (e.g. Duration)
     * 
     * @param array|string $videoIds
     * @return array
     */
    public function getVideoDetails($videoIds)
    {
        if (is_array($videoIds)) {
            $videoIds = implode(',', $videoIds);
        }

        try {
            $response = Http::get("{$this->baseUrl}/videos", [
                'part' => 'contentDetails,snippet',
                'id' => $videoIds,
                'key' => $this->apiKey,
            ]);

            if ($response->failed()) {
                Log::error('YouTube API Video Details Error: ' . $response->body());
                return ['error' => 'YouTube API request failed'];
            }

            return $response->json();
        } catch (\Exception $e) {
             Log::error('YouTube Service Details Exception: ' . $e->getMessage());
             return ['error' => $e->getMessage()];
        }
    }
    /**
     * Search and return the SINGLE best match for a music track
     * 
     * @param string $query
     * @return array|null Clean track data or null
     */
    public function findBestMatch(string $query)
    {
        // 1. Search for a broader set of results to filter from
        $results = $this->search($query, 10);
        
        if (isset($results['error']) || empty($results['items'])) {
            return null;
        }

        $items = $results['items'];
        $scoredItems = [];

        foreach ($items as $item) {
            $score = 0;
            $title = $item['snippet']['title'];
            $channel = $item['snippet']['channelTitle'];
            $description = $item['snippet']['description'];

            // LOWERCASE comparison
            $lTitle = mb_strtolower($title);
            $lChannel = mb_strtolower($channel);

            // --- POSITIVE SIGNALS ---
            
            // "Topic" channels are auto-generated by YouTube from official distribution
            if (str_contains($lChannel, ' - topic')) {
                $score += 50; 
            }
            
            // Official VEVO channels
            if (str_contains($lChannel, 'vevo')) {
                $score += 20;
            }

            // Official Keywords
            if (str_contains($lTitle, 'official audio')) {
                $score += 30;
            } elseif (str_contains($lTitle, 'official video')) {
                $score += 20; // Audio is preferred over video usually for streaming apps, but video is okay
            } elseif (str_contains($lTitle, 'official lyric video')) {
                $score += 15;
            }

            // --- NEGATIVE SIGNALS (Filter out garbage) ---
            
            // We want the official track, not random live recordings
            if (str_contains($lTitle, 'live') && !str_contains($query, 'live')) {
                $score -= 40;
            }
            
            // Filter covers unless asked for
            if ((str_contains($lTitle, 'cover') || str_contains($lChannel, 'cover')) && !str_contains($query, 'cover')) {
                $score -= 50;
            }

            // Filter "reaction" videos
            if (str_contains($lTitle, 'reaction') || str_contains($lTitle, 'react to')) {
                $score -= 100;
            }
            
            // Filter "review"
            if (str_contains($lTitle, 'review')) {
                $score -= 100;
            }

            // Filter "1 hour version", "slowed"
            if (str_contains($lTitle, '1 hour') || str_contains($lTitle, 'slowed')) {
                $score -= 30;
            }

            $scoredItems[] = [
                'item' => $item,
                'score' => $score
            ];
        }

        // Sort by Score DESC
        usort($scoredItems, function ($a, $b) {
            return $b['score'] <=> $a['score'];
        });

        // Take the winner
        $bestItem = $scoredItems[0]['item'];

        return $this->formatTrackData($bestItem);
    }

    /**
     * Helper: Select best thumbnail and format data
     */
    protected function formatTrackData($item)
    {
        $snippet = $item['snippet'];
        $thumbnails = $snippet['thumbnails'];
        
        // Priority: maxres > standard > high > medium > default
        $coverUrl = $thumbnails['maxres']['url'] 
            ?? $thumbnails['standard']['url'] 
            ?? $thumbnails['high']['url'] 
            ?? $thumbnails['medium']['url'] 
            ?? $thumbnails['default']['url'];

        return [
            'id' => $item['id']['videoId'],
            'title' => $snippet['title'],
            'channel' => $snippet['channelTitle'],
            'description' => $snippet['description'],
            'cover_image' => $coverUrl,
            'published_at' => $snippet['publishedAt']
        ];
    }
}
